#!/bin/bash
#SBATCH --job-name=dev_sem_vcorr
#SBATCH --partition=dev_gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50G
#SBATCH --time=00:30:00
#SBATCH --output=jobs_with_target_guidance/cross_animal_spike_runs/logs/dev_sem_vcorr_%j.out
#SBATCH --error=jobs_with_target_guidance/cross_animal_spike_runs/logs/dev_sem_vcorr_%j.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=latifajrona@gmail.com

set -euo pipefail

if [[ "$#" -lt 1 ]]; then
  echo "Usage: sbatch $0 PAIR_ID"
  echo "PAIR_ID: 0 dachshund->golden, 1 golden->dachshund, 2 dachshund->cat, 3 cat->dachshund, 4 bulldog->cat, 5 cat->bulldog, 6 bulldog->dachshund, 7 dachshund->bulldog"
  exit 2
fi

cd /pfs/work9/workspace/scratch/fr_rl187-my_project_ws/projects/meshup_v2

PAIR_ID="$1"
BASE_DIR=${BASE_DIR:-./jobs_with_target_guidance/cross_animal_spike_runs}
EPOCHS=${EPOCHS:-2500}
RUN_TAG=${RUN_TAG:-semantic_vcorr_dev_h100}
OUTPUT_ROOT=${OUTPUT_ROOT:-${BASE_DIR}/outputs/semantic_vcorr_partfield}

mkdir -p "${OUTPUT_ROOT}" "${BASE_DIR}/logs" "${BASE_DIR}/correspondences"

export TARGET_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_VERTEX_CORRESPONDENCE_WEIGHT:-0.0}
export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT:-20000.0}
export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS:-0}
export SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER:-soft}
export SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT:-1.0}
export SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT:-0.20}
export SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT:-0.05}
export SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY:-0.25}
export SEMANTIC_VERTEX_CORRESPONDENCE_TOPK=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPK:-32}
export SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY=${SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY:-0.05}
export SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN:-0.04}
export SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR:-0.25}
export SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT:-0.60}
export SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT:-0.20}
export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=${GLOBAL_CHAMFER_WEIGHT_OVERRIDE:-0.0}
export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=${PARTFIELD_CHAMFER_WEIGHT_OVERRIDE:-0.0}
export DEFORMATION_PARAMETERIZATION=${DEFORMATION_PARAMETERIZATION:-vertex}
export VARIANT_SUFFIX=${VARIANT_SUFFIX:-semantic_vcorr20000_pf_topoprior020}

bash "${BASE_DIR}/jobs/run_cross_animal_best_pair.sh" \
  "${PAIR_ID}" \
  "${EPOCHS}" \
  "${OUTPUT_ROOT}" \
  "${RUN_TAG}"
