#!/bin/bash
set -euo pipefail

if [[ "$#" -lt 5 ]]; then
  echo "Usage: $0 PAIR_ID MESH_VARIANT EPOCHS OUTPUT_ROOT RUN_TAG"
  echo "PAIR_ID: 0 giraffe->elephant, 1 elephant->giraffe, 2 bear->cheetah, 3 cheetah->bear, 4 panther->bear, 5 bear->panther, 6 moose->elephant, 7 elephant->moose, 8 panther->cheetah, 9 cheetah->panther, 10 bear->elephant"
  echo "MESH_VARIANT: full, 5k, or any prepared suffix such as bucketaverage4998"
  exit 2
fi

PAIR_ID="$1"
MESH_VARIANT="$2"
EPOCHS="$3"
OUTPUT_ROOT="$4"
RUN_TAG="$5"

cd /pfs/work9/workspace/scratch/fr_rl187-my_project_ws/projects/meshup_v2

BASE_DIR=${BASE_DIR:-./jobs_with_target_guidance/cross_animal_spike_runs}
PREPARED_DIR=${PREPARED_DIR:-./jobs_with_target_guidance/densematcher_runs/prepared/requested_animals_20260630}

# Preserve explicit submit-time overrides before the defaults/presets below
# populate the same variables.
REQUESTED_EDGE_STRETCH_WEIGHT=${EDGE_STRETCH_WEIGHT:-}
REQUESTED_EDGE_STRETCH_THRESHOLD=${EDGE_STRETCH_THRESHOLD:-}
REQUESTED_EDGE_STRETCH_MAX_WEIGHT=${EDGE_STRETCH_MAX_WEIGHT:-}
REQUESTED_EDGE_DISPLACEMENT_JUMP_WEIGHT=${EDGE_DISPLACEMENT_JUMP_WEIGHT:-}
REQUESTED_EDGE_DISPLACEMENT_JUMP_THRESHOLD=${EDGE_DISPLACEMENT_JUMP_THRESHOLD:-}
REQUESTED_EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT:-}
REQUESTED_DEFORMATION_GRAD_CLIP_NORM=${DEFORMATION_GRAD_CLIP_NORM:-}
REQUESTED_VARIANT_SUFFIX=${VARIANT_SUFFIX:-}

if [[ ! "${MESH_VARIANT}" =~ ^[A-Za-z0-9_.-]+$ ]]; then
  echo "Unsafe MESH_VARIANT=${MESH_VARIANT}. Use only letters, digits, '.', '_', or '-'."
  exit 2
fi

animal_object_id() {
  case "$1" in
    elephant) echo "2d6b3_toy_animals_009" ;;
    moose) echo "1d6d1_toy_animals_015" ;;
    giraffe) echo "34fb4_toy_animals_019" ;;
    panther) echo "071b8_toy_animals_017" ;;
    bear) echo "96615_toy_animals_018" ;;
    cheetah) echo "bdfd0_toy_animals_016" ;;
    *)
      echo "Unknown animal key: $1" >&2
      return 2
      ;;
  esac
}

animal_prompt() {
  case "$1" in
    elephant) echo "an elephant" ;;
    moose) echo "a moose" ;;
    giraffe) echo "a giraffe" ;;
    panther) echo "a panther" ;;
    bear) echo "a bear" ;;
    cheetah) echo "a cheetah" ;;
    *)
      echo "Unknown animal key: $1" >&2
      return 2
      ;;
  esac
}

case "${PAIR_ID}" in
  0)
    SOURCE_ANIMAL=giraffe
    TARGET_ANIMAL=elephant
    ;;
  1)
    SOURCE_ANIMAL=elephant
    TARGET_ANIMAL=giraffe
    ;;
  2)
    SOURCE_ANIMAL=bear
    TARGET_ANIMAL=cheetah
    ;;
  3)
    SOURCE_ANIMAL=cheetah
    TARGET_ANIMAL=bear
    ;;
  4)
    SOURCE_ANIMAL=panther
    TARGET_ANIMAL=bear
    ;;
  5)
    SOURCE_ANIMAL=bear
    TARGET_ANIMAL=panther
    ;;
  6)
    SOURCE_ANIMAL=moose
    TARGET_ANIMAL=elephant
    ;;
  7)
    SOURCE_ANIMAL=elephant
    TARGET_ANIMAL=moose
    ;;
  8)
    SOURCE_ANIMAL=panther
    TARGET_ANIMAL=cheetah
    ;;
  9)
    SOURCE_ANIMAL=cheetah
    TARGET_ANIMAL=panther
    ;;
  10)
    SOURCE_ANIMAL=bear
    TARGET_ANIMAL=elephant
    ;;
  *)
    echo "Unknown PAIR_ID=${PAIR_ID}. Expected 0..10."
    exit 2
    ;;
esac

SOURCE_OBJECT=$(animal_object_id "${SOURCE_ANIMAL}")
TARGET_OBJECT=$(animal_object_id "${TARGET_ANIMAL}")

export PAIR_SLUG="${SOURCE_ANIMAL}_to_${TARGET_ANIMAL}_${MESH_VARIANT}"
export SOURCE="${PREPARED_DIR}/meshes/${SOURCE_OBJECT}_densecorr3d_${MESH_VARIANT}.obj"
export TARGET="${PREPARED_DIR}/meshes/${TARGET_OBJECT}_densecorr3d_${MESH_VARIANT}.obj"
export SOURCE_NAME="${SOURCE_OBJECT}_densecorr3d_${MESH_VARIANT}"
export TARGET_NAME="${TARGET_OBJECT}_densecorr3d_${MESH_VARIANT}"
export PROMPT
PROMPT=$(animal_prompt "${TARGET_ANIMAL}")

export SOURCE_PARTFIELD_LABELS="${PREPARED_DIR}/labels/${SOURCE_OBJECT}_densecorr3d_${MESH_VARIANT}_labels.npz"
export TARGET_PARTFIELD_LABELS="${PREPARED_DIR}/labels/${TARGET_OBJECT}_densecorr3d_${MESH_VARIANT}_labels.npz"

for path in "${SOURCE}" "${TARGET}" "${SOURCE_PARTFIELD_LABELS}" "${TARGET_PARTFIELD_LABELS}"; do
  if [[ ! -f "${path}" ]]; then
    echo "Missing required DenseCorr3D prepared input: ${path}"
    exit 1
  fi
done

export PARTFIELD_USE_FEATURES=0
export PARTFIELD_N_BUCKETS=8
export PARTFIELD_LABELS_ALIGNED=1

export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
export DEFORMATION_PARAMETERIZATION=jacobian
export JACOBIAN_REG_WEIGHT=0.0
export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
export JACOBIAN_OUTLIER_WEIGHT=0.0
export JACOBIAN_OUTLIER_POWER=4.0
export DEFORMATION_GRAD_CLIP_NORM=0.0
export EDGE_STRETCH_WEIGHT=0.0
export EDGE_STRETCH_THRESHOLD=1.5
export EDGE_STRETCH_MAX_WEIGHT=1.0
export EDGE_DISPLACEMENT_JUMP_WEIGHT=500.0
export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.2
export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=2.0

export TARGET_VERTEX_CORRESPONDENCE_WEIGHT=0.0
export TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=0
export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=0.0
export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=0
export SEMANTIC_VERTEX_CORRESPONDENCE_CACHE=
export SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE=0

export TARGET_CHAMFER_WARMUP_EPOCHS=0
export PARTFIELD_CHAMFER_WARMUP_EPOCHS=0
export ENABLE_SOURCE_DINO_LOSS=0
export ENABLE_TARGET_DINO_GUIDANCE=0

export PARTFIELD_GUIDANCE_MODE=hard
export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.35
export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.0
export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
export PARTFIELD_HARD_SEMANTIC_WEIGHT=0.0
export PARTFIELD_HARD_GEOMETRY_SIGMA=1.0
export PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY=-1.0
export PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN=0.0
export PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR=1.0
export PARTFIELD_SEMANTIC_CONFIDENCE_POWER=1.0
export PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT=0.0
export PARTFIELD_UNBALANCED_TRANSPORT_RHO=0.30
export ARTUR_SOFT_MATCH_SPACE=hybrid
export ARTUR_SOFT_POINTS=1024
export ARTUR_SOFT_GEOMETRY_SIGMA=0.5
export ARTUR_SOFT_SEMANTIC_WEIGHT=1.0
export ARTUR_SOFT_TEMPERATURE=0.1
export PARTFIELD_BALANCED_SINKHORN_ITERS=30
export PARTFIELD_MIN_POINTS=12
export PARTFIELD_CONTAINMENT_WEIGHT=0.0
export PARTFIELD_CONTAINMENT_MARGIN=0.02
export PARTFIELD_CONTAINMENT_MAX_WEIGHT=1.0
export PARTFIELD_MOMENT_WEIGHT=0.0
export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
export PARTFIELD_PROFILE_WEIGHT=0.0
export PARTFIELD_PROFILE_BINS=9
export PARTFIELD_PROFILE_TRIM=0.08
export PARTFIELD_ANCHOR_WEIGHT=0.0
export PARTFIELD_ANCHOR_GEOMETRY_SIGMA=0.35
export PARTFIELD_ANCHOR_SEMANTIC_WEIGHT=0.50

export LOG_INTERVAL_IM=250
export SAVE_RENDERS_INTERVAL=250
export SAVE_PCA_VISUALIZATION=0
export PCA_INTERVAL=250
export PCA_N_VIEWS=8
export PCA_RENDER_RES=518
export PCA_DINO_MODEL=dinov2_vitl14
export PCA_USE_EXTRA_LOG_EPOCHS=0
export VARIANT_SUFFIX=densecorr3d_groups_pfonly_best_asym035_jneighbor1000_jump500

case "${DENSECORR3D_REPAIR_PRESET:-}" in
  "")
    ;;
  ge5k_profile_robust)
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=75.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=6000.0
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.45
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=0.60
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.05
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=0.70
    export PARTFIELD_MOMENT_WEIGHT=0.20
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=1.00
    export PARTFIELD_PROFILE_WEIGHT=0.35
    export PARTFIELD_ANCHOR_WEIGHT=0.25
    export PARTFIELD_CONTAINMENT_WEIGHT=0.15
    export PARTFIELD_CONTAINMENT_MARGIN=0.01
    export PARTFIELD_CONTAINMENT_MAX_WEIGHT=1.5
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1500.0
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=1000.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=0.9
    export VARIANT_SUFFIX=densecorr3d_groups_ge5k_profile_robust_t2s060_robust005_m020_e100_p035_a025_c015_j1500_jump1000
    ;;
  ge5k_balanced_profile)
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=100.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=5000.0
    export PARTFIELD_GUIDANCE_MODE=balanced
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.50
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=0.50
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.05
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=0.70
    export PARTFIELD_MOMENT_WEIGHT=0.18
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=1.00
    export PARTFIELD_PROFILE_WEIGHT=0.40
    export PARTFIELD_ANCHOR_WEIGHT=0.20
    export PARTFIELD_CONTAINMENT_WEIGHT=0.20
    export PARTFIELD_CONTAINMENT_MARGIN=0.01
    export PARTFIELD_CONTAINMENT_MAX_WEIGHT=1.5
    export PARTFIELD_BALANCED_SINKHORN_ITERS=50
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1500.0
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=1000.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=0.9
    export VARIANT_SUFFIX=densecorr3d_groups_ge5k_balanced_profile_global100_m018_e100_p040_a020_c020_j1500_jump1000
    ;;
  ge5k_spikeguard_only)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.35
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.00
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=2500.0
    export DEFORMATION_GRAD_CLIP_NORM=1.0
    export EDGE_STRETCH_WEIGHT=150.0
    export EDGE_STRETCH_THRESHOLD=1.7
    export EDGE_STRETCH_MAX_WEIGHT=4.0
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=2500.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=0.75
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=4.0
    export VARIANT_SUFFIX=densecorr3d_groups_spikeguard_only_pf8000_j2500_jump2500_edge150
    ;;
  ge5k_mild_spikeguard)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.35
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.00
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
    export DEFORMATION_GRAD_CLIP_NORM=0.0
    export EDGE_STRETCH_WEIGHT=35.0
    export EDGE_STRETCH_THRESHOLD=2.5
    export EDGE_STRETCH_MAX_WEIGHT=1.5
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=900.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.05
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=1.5
    export VARIANT_SUFFIX=densecorr3d_groups_mild_spikeguard_pf8000_j1000_jump900_edge35
    ;;
  ge5k_balanced_mild)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
    export PARTFIELD_GUIDANCE_MODE=balanced
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.50
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=0.50
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export PARTFIELD_BALANCED_SINKHORN_ITERS=60
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
    export DEFORMATION_GRAD_CLIP_NORM=0.0
    export EDGE_STRETCH_WEIGHT=35.0
    export EDGE_STRETCH_THRESHOLD=2.5
    export EDGE_STRETCH_MAX_WEIGHT=1.5
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=900.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.05
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=1.5
    export VARIANT_SUFFIX=densecorr3d_groups_balanced_mild_pf8000_b60_j1000_jump900_edge35
    ;;
  ge5k_robust_mild)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=7500.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.40
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=0.75
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.04
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=0.85
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
    export DEFORMATION_GRAD_CLIP_NORM=0.0
    export EDGE_STRETCH_WEIGHT=35.0
    export EDGE_STRETCH_THRESHOLD=2.5
    export EDGE_STRETCH_MAX_WEIGHT=1.5
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=900.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.05
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=1.5
    export VARIANT_SUFFIX=densecorr3d_groups_robust_mild_pf7500_s2t040_t2s075_r004_j1000_jump900_edge35
    ;;
  ge5k_headneck_union_mild)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    UNION_DIR="${PREPARED_DIR}/refined/giraffe_to_elephant_5k_headneck_union"
    export SOURCE_PARTFIELD_LABELS="${UNION_DIR}/labels/giraffe_to_elephant_5k_headneck_union_source_labels.npz"
    export TARGET_PARTFIELD_LABELS="${UNION_DIR}/labels/giraffe_to_elephant_5k_headneck_union_target_labels.npz"
    export PARTFIELD_USE_FEATURES=0
    export PARTFIELD_N_BUCKETS=6
    export PARTFIELD_LABELS_ALIGNED=1
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.25
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.15
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
    export DEFORMATION_GRAD_CLIP_NORM=0.0
    export EDGE_STRETCH_WEIGHT=35.0
    export EDGE_STRETCH_THRESHOLD=2.5
    export EDGE_STRETCH_MAX_WEIGHT=1.5
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=900.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.05
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=1.5
    export VARIANT_SUFFIX=densecorr3d_headneck_union6_mild_pf8000_t2s115_s2t025_j1000_jump900_edge35
    ;;
  ge5k_headneck_nohorn_mild)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    NOHORN_DIR="${PREPARED_DIR}/refined/giraffe_to_elephant_5k_headneck_nohorn"
    export SOURCE_PARTFIELD_LABELS="${NOHORN_DIR}/labels/giraffe_to_elephant_5k_headneck_nohorn_source_labels.npz"
    export TARGET_PARTFIELD_LABELS="${NOHORN_DIR}/labels/giraffe_to_elephant_5k_headneck_nohorn_target_labels.npz"
    export PARTFIELD_USE_FEATURES=0
    export PARTFIELD_N_BUCKETS=7
    export PARTFIELD_LABELS_ALIGNED=1
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8000.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.25
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.15
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=1000.0
    export DEFORMATION_GRAD_CLIP_NORM=0.0
    export EDGE_STRETCH_WEIGHT=35.0
    export EDGE_STRETCH_THRESHOLD=2.5
    export EDGE_STRETCH_MAX_WEIGHT=1.5
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=900.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=1.05
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=1.5
    export VARIANT_SUFFIX=densecorr3d_headneck_nohorn7_mild_pf8000_t2s115_s2t025_j1000_jump900_edge35
    ;;
  ge5k_refined32_local|ge5k_refined32_anchor)
    if [[ "${PAIR_ID}" != "0" || "${MESH_VARIANT}" != "5k" ]]; then
      echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET} is only prepared for giraffe->elephant 5k."
      exit 2
    fi
    REFINED_DIR="${PREPARED_DIR}/refined/giraffe_to_elephant_5k_parent4q_min12"
    export SOURCE_PARTFIELD_LABELS="${REFINED_DIR}/labels/giraffe_to_elephant_5k_parent4q_min12_source_labels.npz"
    export TARGET_PARTFIELD_LABELS="${REFINED_DIR}/labels/giraffe_to_elephant_5k_parent4q_min12_target_labels.npz"
    export SOURCE_PARTFIELD_FEATURES="${REFINED_DIR}/features/giraffe_to_elephant_5k_parent4q_min12_source_onehot.npy"
    export TARGET_PARTFIELD_FEATURES="${REFINED_DIR}/features/giraffe_to_elephant_5k_parent4q_min12_target_onehot.npy"
    export PARTFIELD_USE_FEATURES=1
    export PARTFIELD_N_BUCKETS=32
    export PARTFIELD_MIN_POINTS=12
    export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=0.0
    export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=9000.0
    export PARTFIELD_GUIDANCE_MODE=hard
    export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=0.35
    export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=1.00
    export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=0.0
    export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=1.0
    export PARTFIELD_MOMENT_WEIGHT=0.0
    export PARTFIELD_MOMENT_EXTENT_WEIGHT=0.0
    export PARTFIELD_PROFILE_WEIGHT=0.0
    export PARTFIELD_ANCHOR_WEIGHT=0.0
    export PARTFIELD_CONTAINMENT_WEIGHT=0.0
    export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=2500.0
    export DEFORMATION_GRAD_CLIP_NORM=1.0
    export EDGE_STRETCH_WEIGHT=150.0
    export EDGE_STRETCH_THRESHOLD=1.7
    export EDGE_STRETCH_MAX_WEIGHT=4.0
    export EDGE_DISPLACEMENT_JUMP_WEIGHT=2500.0
    export EDGE_DISPLACEMENT_JUMP_THRESHOLD=0.75
    export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=4.0
    export VARIANT_SUFFIX=densecorr3d_parent32q_local_pf9000_j2500_jump2500_edge150
    if [[ "${DENSECORR3D_REPAIR_PRESET}" == "ge5k_refined32_anchor" ]]; then
      export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=8500.0
      export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=250.0
      export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=100
      export SEMANTIC_VERTEX_CORRESPONDENCE_CACHE="${BASE_DIR}/caches/giraffe_to_elephant_5k_parent32q_semv/source_to_target.npz"
      export SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE=1
      export SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER=hard
      export SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT=2.0
      export SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT=0.80
      export SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT=0.05
      export SEMANTIC_VERTEX_CORRESPONDENCE_TOPK=96
      export SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY=0.05
      export SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN=0.02
      export SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR=0.40
      export SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT=0.70
      export VARIANT_SUFFIX=densecorr3d_parent32q_local_semv250_pf8500_j2500_jump2500_edge150
    fi
    ;;
  *)
    echo "Unknown DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET}. Expected ge5k_profile_robust, ge5k_balanced_profile, ge5k_spikeguard_only, ge5k_mild_spikeguard, ge5k_balanced_mild, ge5k_robust_mild, ge5k_headneck_union_mild, ge5k_headneck_nohorn_mild, ge5k_refined32_local, or ge5k_refined32_anchor."
    exit 2
    ;;
esac

apply_requested_override() {
  local name="$1"
  local value="$2"
  if [[ -n "${value}" ]]; then
    export "${name}=${value}"
  fi
}

apply_requested_override EDGE_STRETCH_WEIGHT "${REQUESTED_EDGE_STRETCH_WEIGHT}"
apply_requested_override EDGE_STRETCH_THRESHOLD "${REQUESTED_EDGE_STRETCH_THRESHOLD}"
apply_requested_override EDGE_STRETCH_MAX_WEIGHT "${REQUESTED_EDGE_STRETCH_MAX_WEIGHT}"
apply_requested_override EDGE_DISPLACEMENT_JUMP_WEIGHT "${REQUESTED_EDGE_DISPLACEMENT_JUMP_WEIGHT}"
apply_requested_override EDGE_DISPLACEMENT_JUMP_THRESHOLD "${REQUESTED_EDGE_DISPLACEMENT_JUMP_THRESHOLD}"
apply_requested_override EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT "${REQUESTED_EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT}"
apply_requested_override DEFORMATION_GRAD_CLIP_NORM "${REQUESTED_DEFORMATION_GRAD_CLIP_NORM}"
apply_requested_override VARIANT_SUFFIX "${REQUESTED_VARIANT_SUFFIX}"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "PAIR_SLUG=${PAIR_SLUG}"
  echo "SOURCE=${SOURCE}"
  echo "TARGET=${TARGET}"
  echo "SOURCE_PARTFIELD_LABELS=${SOURCE_PARTFIELD_LABELS}"
  echo "TARGET_PARTFIELD_LABELS=${TARGET_PARTFIELD_LABELS}"
  echo "PROMPT=${PROMPT}"
  echo "MESH_VARIANT=${MESH_VARIANT}"
  echo "PARTFIELD_N_BUCKETS=${PARTFIELD_N_BUCKETS}"
  echo "PARTFIELD_LABELS_ALIGNED=${PARTFIELD_LABELS_ALIGNED}"
  echo "PARTFIELD_USE_FEATURES=${PARTFIELD_USE_FEATURES}"
  echo "DENSECORR3D_REPAIR_PRESET=${DENSECORR3D_REPAIR_PRESET:-}"
  echo "GLOBAL_CHAMFER_WEIGHT_OVERRIDE=${GLOBAL_CHAMFER_WEIGHT_OVERRIDE}"
  echo "PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=${PARTFIELD_CHAMFER_WEIGHT_OVERRIDE}"
  echo "PARTFIELD_GUIDANCE_MODE=${PARTFIELD_GUIDANCE_MODE}"
  echo "PARTFIELD_SOURCE_TO_TARGET_WEIGHT=${PARTFIELD_SOURCE_TO_TARGET_WEIGHT}"
  echo "PARTFIELD_TARGET_TO_SOURCE_WEIGHT=${PARTFIELD_TARGET_TO_SOURCE_WEIGHT}"
  echo "PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=${PARTFIELD_TGT_TO_SRC_ROBUST_SCALE}"
  echo "PARTFIELD_MOMENT_WEIGHT=${PARTFIELD_MOMENT_WEIGHT}"
  echo "PARTFIELD_MOMENT_EXTENT_WEIGHT=${PARTFIELD_MOMENT_EXTENT_WEIGHT}"
  echo "PARTFIELD_PROFILE_WEIGHT=${PARTFIELD_PROFILE_WEIGHT}"
  echo "PARTFIELD_ANCHOR_WEIGHT=${PARTFIELD_ANCHOR_WEIGHT}"
  echo "PARTFIELD_CONTAINMENT_WEIGHT=${PARTFIELD_CONTAINMENT_WEIGHT}"
  echo "JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=${JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT}"
  echo "EDGE_STRETCH_WEIGHT=${EDGE_STRETCH_WEIGHT}"
  echo "EDGE_STRETCH_THRESHOLD=${EDGE_STRETCH_THRESHOLD}"
  echo "EDGE_STRETCH_MAX_WEIGHT=${EDGE_STRETCH_MAX_WEIGHT}"
  echo "EDGE_DISPLACEMENT_JUMP_WEIGHT=${EDGE_DISPLACEMENT_JUMP_WEIGHT}"
  echo "EDGE_DISPLACEMENT_JUMP_THRESHOLD=${EDGE_DISPLACEMENT_JUMP_THRESHOLD}"
  echo "EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT}"
  echo "VARIANT_SUFFIX=${VARIANT_SUFFIX}"
  exit 0
fi

bash ./jobs_with_target_guidance/artur_soft_runs/jobs/run_artur_chamfer_ablation.sh \
  1 \
  "${EPOCHS}" \
  "${OUTPUT_ROOT}" \
  "${RUN_TAG}"
