#!/bin/bash
set -euo pipefail

if [[ "$#" -lt 4 ]]; then
  echo "Usage: $0 VARIANT_ID EPOCHS OUTPUT_ROOT RUN_TAG"
  exit 2
fi

VARIANT_ID="$1"
EPOCHS="$2"
OUTPUT_ROOT="$3"
RUN_TAG="$4"

cd /pfs/work9/workspace/scratch/fr_rl187-my_project_ws/projects/meshup_v2
mkdir -p "${OUTPUT_ROOT}" jobs_with_target_guidance/artur_soft_runs/logs

source ./activate_meshup_new.sh

SOURCE=${SOURCE:-./experiments/dog_morphs/outputs/hound_to_bulldog_exp/mesh_final/mesh.obj}
TARGET=${TARGET:-./experiments/dog_morphs/outputs/hound_to_dachshund_exp/mesh_final/mesh.obj}
SOURCE_NAME=${SOURCE_NAME:-hound_to_bulldog}
TARGET_NAME=${TARGET_NAME:-hound_to_dachshund}
PAIR_SLUG=${PAIR_SLUG:-bulldog_to_dachshund}
PROMPT=${PROMPT:-"a dog"}

PARTFIELD_FEATURE_DIR=${PARTFIELD_FEATURE_DIR:-./jobs_with_target_guidance/partfield_features/test_meshes}
SOURCE_PARTFIELD_FEATURE_DIR=${SOURCE_PARTFIELD_FEATURE_DIR:-${PARTFIELD_FEATURE_DIR}}
TARGET_PARTFIELD_FEATURE_DIR=${TARGET_PARTFIELD_FEATURE_DIR:-${PARTFIELD_FEATURE_DIR}}
PARTFIELD_LABEL_DIR=${PARTFIELD_LABEL_DIR:-./jobs_with_target_guidance/partfield_segments/dachshund_bulldog_12/labels}
SOURCE_PARTFIELD_LABEL_DIR=${SOURCE_PARTFIELD_LABEL_DIR:-${PARTFIELD_LABEL_DIR}}
TARGET_PARTFIELD_LABEL_DIR=${TARGET_PARTFIELD_LABEL_DIR:-${PARTFIELD_LABEL_DIR}}
SOURCE_PARTFIELD_LABELS=${SOURCE_PARTFIELD_LABELS:-${SOURCE_PARTFIELD_LABEL_DIR}/${SOURCE_NAME}_partfield_labels.npz}
TARGET_PARTFIELD_LABELS=${TARGET_PARTFIELD_LABELS:-${TARGET_PARTFIELD_LABEL_DIR}/${TARGET_NAME}_partfield_labels.npz}
SOURCE_PARTFIELD_FEATURES=${SOURCE_PARTFIELD_FEATURES:-${SOURCE_PARTFIELD_FEATURE_DIR}/part_feat_${SOURCE_NAME}_0_batch.npy}
TARGET_PARTFIELD_FEATURES=${TARGET_PARTFIELD_FEATURES:-${TARGET_PARTFIELD_FEATURE_DIR}/part_feat_${TARGET_NAME}_0_batch.npy}
PARTFIELD_USE_FEATURES=${PARTFIELD_USE_FEATURES:-1}

N_BUCKETS=${PARTFIELD_N_BUCKETS:-12}
PARTFIELD_MIN_POINTS=${PARTFIELD_MIN_POINTS:-12}
DEFORMATION_PARAMETERIZATION=${DEFORMATION_PARAMETERIZATION:-jacobian}
JACOBIAN_REG_WEIGHT=${JACOBIAN_REG_WEIGHT:-0.0}
JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=${JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT:-0.0}
JACOBIAN_OUTLIER_WEIGHT=${JACOBIAN_OUTLIER_WEIGHT:-0.0}
JACOBIAN_OUTLIER_POWER=${JACOBIAN_OUTLIER_POWER:-4.0}
DEFORMATION_GRAD_CLIP_NORM=${DEFORMATION_GRAD_CLIP_NORM:-0.0}
EDGE_STRETCH_WEIGHT=${EDGE_STRETCH_WEIGHT:-0.0}
EDGE_STRETCH_THRESHOLD=${EDGE_STRETCH_THRESHOLD:-1.5}
EDGE_STRETCH_MAX_WEIGHT=${EDGE_STRETCH_MAX_WEIGHT:-1.0}
EDGE_DISPLACEMENT_JUMP_WEIGHT=${EDGE_DISPLACEMENT_JUMP_WEIGHT:-0.0}
EDGE_DISPLACEMENT_JUMP_THRESHOLD=${EDGE_DISPLACEMENT_JUMP_THRESHOLD:-1.25}
EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT:-1.0}
TARGET_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_VERTEX_CORRESPONDENCE_WEIGHT:-0.0}
TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=${TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS:-0}
TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT:-0.0}
TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS:-0}
SEMANTIC_VERTEX_CORRESPONDENCE_CACHE=${SEMANTIC_VERTEX_CORRESPONDENCE_CACHE:-}
SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE=${SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE:-0}
SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER:-soft}
SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT:-1.0}
SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT:-0.20}
SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT:-0.05}
SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY:-0.25}
SEMANTIC_VERTEX_CORRESPONDENCE_TOPK=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPK:-32}
SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY=${SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY:-0.05}
SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN:-0.04}
SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR:-0.25}
SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT:-0.60}
SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT:-0.0}
TARGET_CHAMFER_WARMUP_EPOCHS=${TARGET_CHAMFER_WARMUP_EPOCHS:-0}
PARTFIELD_CHAMFER_WARMUP_EPOCHS=${PARTFIELD_CHAMFER_WARMUP_EPOCHS:-0}
LOG_INTERVAL_IM=${LOG_INTERVAL_IM:-250}
SAVE_RENDERS_INTERVAL=${SAVE_RENDERS_INTERVAL:-${LOG_INTERVAL_IM}}
SAVE_PCA_VISUALIZATION=${SAVE_PCA_VISUALIZATION:-0}
PCA_INTERVAL=${PCA_INTERVAL:-${LOG_INTERVAL_IM}}
PCA_N_VIEWS=${PCA_N_VIEWS:-8}
PCA_RENDER_RES=${PCA_RENDER_RES:-518}
PCA_DINO_MODEL=${PCA_DINO_MODEL:-dinov2_vitl14}
PCA_USE_EXTRA_LOG_EPOCHS=${PCA_USE_EXTRA_LOG_EPOCHS:-0}
GLOBAL_CHAMFER_WEIGHT=0.0
PARTFIELD_CHAMFER_WEIGHT=0.0
PARTFIELD_GUIDANCE_MODE_OVERRIDE=${PARTFIELD_GUIDANCE_MODE:-}
PARTFIELD_HARD_WEIGHT_OVERRIDE=${PARTFIELD_HARD_WEIGHT:-}
PARTFIELD_SOFT_WEIGHT_OVERRIDE=${PARTFIELD_SOFT_WEIGHT:-}
PARTFIELD_GUIDANCE_MODE=hard
PARTFIELD_HARD_WEIGHT=0.0
PARTFIELD_SOURCE_TO_TARGET_WEIGHT=${PARTFIELD_SOURCE_TO_TARGET_WEIGHT:-1.0}
PARTFIELD_TARGET_TO_SOURCE_WEIGHT=${PARTFIELD_TARGET_TO_SOURCE_WEIGHT:-1.0}
PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=${PARTFIELD_TGT_TO_SRC_ROBUST_SCALE:-0.0}
PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=${PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT:-1.0}
PARTFIELD_HARD_SEMANTIC_WEIGHT=${PARTFIELD_HARD_SEMANTIC_WEIGHT:-0.0}
PARTFIELD_HARD_GEOMETRY_SIGMA=${PARTFIELD_HARD_GEOMETRY_SIGMA:-1.0}
PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY=${PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY:--1.0}
PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN=${PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN:-0.0}
PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR=${PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR:-1.0}
PARTFIELD_SEMANTIC_CONFIDENCE_POWER=${PARTFIELD_SEMANTIC_CONFIDENCE_POWER:-1.0}
PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT=${PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT:-0.0}
PARTFIELD_UNBALANCED_TRANSPORT_RHO=${PARTFIELD_UNBALANCED_TRANSPORT_RHO:-0.30}
PARTFIELD_SOFT_WEIGHT=0.0
ARTUR_SOFT_MATCH_SPACE=${ARTUR_SOFT_MATCH_SPACE:-hybrid}
ARTUR_SOFT_POINTS=${ARTUR_SOFT_POINTS:-1024}
ARTUR_SOFT_GEOMETRY_SIGMA=${ARTUR_SOFT_GEOMETRY_SIGMA:-0.5}
ARTUR_SOFT_SEMANTIC_WEIGHT=${ARTUR_SOFT_SEMANTIC_WEIGHT:-1.0}
ARTUR_SOFT_TEMPERATURE=${ARTUR_SOFT_TEMPERATURE:-0.1}
PARTFIELD_BALANCED_SINKHORN_ITERS=${PARTFIELD_BALANCED_SINKHORN_ITERS:-30}
PARTFIELD_CONTAINMENT_WEIGHT=${PARTFIELD_CONTAINMENT_WEIGHT:-0.0}
PARTFIELD_CONTAINMENT_MARGIN=${PARTFIELD_CONTAINMENT_MARGIN:-0.02}
PARTFIELD_CONTAINMENT_MAX_WEIGHT=${PARTFIELD_CONTAINMENT_MAX_WEIGHT:-1.0}
PARTFIELD_MOMENT_WEIGHT=${PARTFIELD_MOMENT_WEIGHT:-0.0}
PARTFIELD_MOMENT_EXTENT_WEIGHT=${PARTFIELD_MOMENT_EXTENT_WEIGHT:-0.5}
PARTFIELD_PROFILE_WEIGHT=${PARTFIELD_PROFILE_WEIGHT:-0.0}
PARTFIELD_PROFILE_BINS=${PARTFIELD_PROFILE_BINS:-9}
PARTFIELD_PROFILE_TRIM=${PARTFIELD_PROFILE_TRIM:-0.08}
PARTFIELD_ANCHOR_WEIGHT=${PARTFIELD_ANCHOR_WEIGHT:-0.0}
PARTFIELD_ANCHOR_GEOMETRY_SIGMA=${PARTFIELD_ANCHOR_GEOMETRY_SIGMA:-0.35}
PARTFIELD_ANCHOR_SEMANTIC_WEIGHT=${PARTFIELD_ANCHOR_SEMANTIC_WEIGHT:-0.0}
PARTFIELD_LABELS_ALIGNED=${PARTFIELD_LABELS_ALIGNED:-1}

case "${VARIANT_ID}" in
  0)
    VARIANT=global_chamfer_only
    GLOBAL_CHAMFER_WEIGHT=750.0
    ;;
  1)
    VARIANT=hard_partfield_chamfer_only
    PARTFIELD_CHAMFER_WEIGHT=8000.0
    PARTFIELD_GUIDANCE_MODE=hard
    PARTFIELD_HARD_WEIGHT=1.0
    PARTFIELD_SOFT_WEIGHT=0.0
    ;;
  2)
    VARIANT=artur_soft_partfield_chamfer_only
    PARTFIELD_CHAMFER_WEIGHT=8000.0
    PARTFIELD_GUIDANCE_MODE=soft
    PARTFIELD_HARD_WEIGHT=0.0
    PARTFIELD_SOFT_WEIGHT=1.0
    ;;
  *)
    echo "Unknown VARIANT_ID=${VARIANT_ID}. Expected 0, 1, or 2."
    exit 1
    ;;
esac

if [[ -n "${GLOBAL_CHAMFER_WEIGHT_OVERRIDE:-}" ]]; then
  GLOBAL_CHAMFER_WEIGHT="${GLOBAL_CHAMFER_WEIGHT_OVERRIDE}"
fi
if [[ -n "${PARTFIELD_CHAMFER_WEIGHT_OVERRIDE:-}" ]]; then
  PARTFIELD_CHAMFER_WEIGHT="${PARTFIELD_CHAMFER_WEIGHT_OVERRIDE}"
fi
if [[ -n "${PARTFIELD_GUIDANCE_MODE_OVERRIDE}" ]]; then
  PARTFIELD_GUIDANCE_MODE="${PARTFIELD_GUIDANCE_MODE_OVERRIDE}"
fi
if [[ -n "${PARTFIELD_HARD_WEIGHT_OVERRIDE}" ]]; then
  PARTFIELD_HARD_WEIGHT="${PARTFIELD_HARD_WEIGHT_OVERRIDE}"
fi
if [[ -n "${PARTFIELD_SOFT_WEIGHT_OVERRIDE}" ]]; then
  PARTFIELD_SOFT_WEIGHT="${PARTFIELD_SOFT_WEIGHT_OVERRIDE}"
fi
if [[ -n "${VARIANT_SUFFIX:-}" ]]; then
  VARIANT="${VARIANT}_${VARIANT_SUFFIX}"
fi

PARTFIELD_LABEL_ARGS=()
if [[ "${PARTFIELD_LABELS_ALIGNED}" == "1" ]]; then
  PARTFIELD_LABEL_ARGS=(--partfield_labels_aligned)
fi

SEMANTIC_VCORR_CACHE_ARGS=()
if [[ -n "${SEMANTIC_VERTEX_CORRESPONDENCE_CACHE}" ]]; then
  SEMANTIC_VCORR_CACHE_ARGS=(--semantic_vertex_correspondence_cache "${SEMANTIC_VERTEX_CORRESPONDENCE_CACHE}")
fi
SEMANTIC_VCORR_REBUILD_ARGS=(--no-semantic_vertex_correspondence_rebuild_cache)
if [[ "${SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE}" == "1" ]]; then
  SEMANTIC_VCORR_REBUILD_ARGS=(--semantic_vertex_correspondence_rebuild_cache)
fi

DINO_LOSS_ARGS=(--no-use_dino_loss)
if [[ "${ENABLE_SOURCE_DINO_LOSS:-0}" == "1" ]]; then
  DINO_LOSS_ARGS=(
    --use_dino_loss
    --dino_weight "${SOURCE_DINO_WEIGHT:-0.08}"
    --dino_warmup_epochs "${SOURCE_DINO_WARMUP_EPOCHS:-100}"
  )
fi

TARGET_DINO_ARGS=(
  --no-use_target_mesh_guidance
  --target_mesh_weight 0.0
  --target_mesh_render_weight 0.0
)
if [[ "${ENABLE_TARGET_DINO_GUIDANCE:-0}" == "1" ]]; then
  TARGET_DINO_ARGS=(
    --use_target_mesh_guidance
    --target_mesh_weight "${TARGET_DINO_WEIGHT:-130.0}"
    --target_mesh_render_weight "${TARGET_DINO_RENDER_WEIGHT:-8.0}"
    --target_mesh_global_weight "${TARGET_DINO_GLOBAL_WEIGHT:-1.0}"
    --target_mesh_spatial_weight "${TARGET_DINO_SPATIAL_WEIGHT:-4.0}"
    --target_mesh_warmup_epochs "${TARGET_DINO_WARMUP_EPOCHS:-15}"
    --target_mesh_n_azimuths "${TARGET_DINO_N_AZIMUTHS:-16}"
    --target_mesh_n_elevations "${TARGET_DINO_N_ELEVATIONS:-4}"
    --target_mesh_online_render
    --target_mesh_online_cache
    --target_mesh_online_cache_max "${TARGET_DINO_ONLINE_CACHE_MAX:-4096}"
    --target_mesh_view_rounding_deg "${TARGET_DINO_VIEW_ROUNDING_DEG:-5.0}"
    --target_mesh_view_rounding_dist "${TARGET_DINO_VIEW_ROUNDING_DIST:-0.1}"
    --target_mesh_view_rounding_fov "${TARGET_DINO_VIEW_ROUNDING_FOV:-2.0}"
  )
fi

PCA_ARGS=(--no-save_pca_visualization)
if [[ "${SAVE_PCA_VISUALIZATION}" == "1" ]]; then
  PCA_ARGS=(
    --save_pca_visualization
    --pca_interval "${PCA_INTERVAL}"
    --pca_n_views "${PCA_N_VIEWS}"
    --pca_render_res "${PCA_RENDER_RES}"
    --pca_dino_model "${PCA_DINO_MODEL}"
  )
  if [[ "${PCA_USE_EXTRA_LOG_EPOCHS}" == "1" ]]; then
    PCA_ARGS+=(--pca_use_extra_log_epochs)
  fi
fi

REQUIRED_INPUTS=(
  "${SOURCE}"
  "${TARGET}"
  "${SOURCE_PARTFIELD_LABELS}"
  "${TARGET_PARTFIELD_LABELS}"
)
if [[ "${PARTFIELD_USE_FEATURES}" == "1" ]]; then
  REQUIRED_INPUTS+=(
    "${SOURCE_PARTFIELD_FEATURES}"
    "${TARGET_PARTFIELD_FEATURES}"
  )
fi

for path in "${REQUIRED_INPUTS[@]}"; do
  if [[ ! -f "${path}" ]]; then
    echo "Missing required input: ${path}"
    exit 1
  fi
done

PARTFIELD_FEATURE_ARGS=()
if [[ "${PARTFIELD_USE_FEATURES}" == "1" ]]; then
  PARTFIELD_FEATURE_ARGS=(
    --partfield_source_features "${SOURCE_PARTFIELD_FEATURES}"
    --partfield_target_features "${TARGET_PARTFIELD_FEATURES}"
  )
elif [[ "${PARTFIELD_GUIDANCE_MODE}" == "soft" || ( "${PARTFIELD_GUIDANCE_MODE}" == "hybrid" && "${PARTFIELD_SOFT_WEIGHT}" != "0" && "${PARTFIELD_SOFT_WEIGHT}" != "0.0" ) ]]; then
  echo "PARTFIELD_USE_FEATURES=0 cannot run soft/hybrid semantic-feature guidance."
  exit 1
fi

JOB_STEM=${SLURM_JOB_ID:-manual}
OUT=${OUTPUT_ROOT}/${PAIR_SLUG}_${RUN_TAG}_${VARIANT}_${EPOCHS}ep_${JOB_STEM}

echo "======================================================"
echo "Artur soft Chamfer ablation"
echo "VARIANT_ID=${VARIANT_ID}"
echo "VARIANT=${VARIANT}"
echo "EPOCHS=${EPOCHS}"
echo "SOURCE=${SOURCE}"
echo "TARGET=${TARGET}"
echo "PROMPT=${PROMPT}"
echo "GLOBAL_CHAMFER_WEIGHT=${GLOBAL_CHAMFER_WEIGHT}"
echo "PARTFIELD_CHAMFER_WEIGHT=${PARTFIELD_CHAMFER_WEIGHT}"
echo "DEFORMATION_PARAMETERIZATION=${DEFORMATION_PARAMETERIZATION}"
echo "JACOBIAN_REG_WEIGHT=${JACOBIAN_REG_WEIGHT}"
echo "JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=${JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT}"
echo "JACOBIAN_OUTLIER_WEIGHT=${JACOBIAN_OUTLIER_WEIGHT}"
echo "JACOBIAN_OUTLIER_POWER=${JACOBIAN_OUTLIER_POWER}"
echo "DEFORMATION_GRAD_CLIP_NORM=${DEFORMATION_GRAD_CLIP_NORM}"
echo "EDGE_STRETCH_WEIGHT=${EDGE_STRETCH_WEIGHT}"
echo "EDGE_STRETCH_THRESHOLD=${EDGE_STRETCH_THRESHOLD}"
echo "EDGE_STRETCH_MAX_WEIGHT=${EDGE_STRETCH_MAX_WEIGHT}"
echo "EDGE_DISPLACEMENT_JUMP_WEIGHT=${EDGE_DISPLACEMENT_JUMP_WEIGHT}"
echo "EDGE_DISPLACEMENT_JUMP_THRESHOLD=${EDGE_DISPLACEMENT_JUMP_THRESHOLD}"
echo "EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT}"
echo "TARGET_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_VERTEX_CORRESPONDENCE_WEIGHT}"
echo "TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=${TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS}"
echo "TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT}"
echo "TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_CACHE=${SEMANTIC_VERTEX_CORRESPONDENCE_CACHE}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE=${SEMANTIC_VERTEX_CORRESPONDENCE_REBUILD_CACHE}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY=${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_TOPK=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPK}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY=${SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR=${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT}"
echo "SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT=${SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT}"
echo "TARGET_CHAMFER_WARMUP_EPOCHS=${TARGET_CHAMFER_WARMUP_EPOCHS}"
echo "PARTFIELD_CHAMFER_WARMUP_EPOCHS=${PARTFIELD_CHAMFER_WARMUP_EPOCHS}"
echo "ENABLE_SOURCE_DINO_LOSS=${ENABLE_SOURCE_DINO_LOSS:-0}"
echo "ENABLE_TARGET_DINO_GUIDANCE=${ENABLE_TARGET_DINO_GUIDANCE:-0}"
echo "PARTFIELD_GUIDANCE_MODE=${PARTFIELD_GUIDANCE_MODE}"
echo "PARTFIELD_SOURCE_TO_TARGET_WEIGHT=${PARTFIELD_SOURCE_TO_TARGET_WEIGHT}"
echo "PARTFIELD_TARGET_TO_SOURCE_WEIGHT=${PARTFIELD_TARGET_TO_SOURCE_WEIGHT}"
echo "PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=${PARTFIELD_TGT_TO_SRC_ROBUST_SCALE}"
echo "PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=${PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT}"
echo "PARTFIELD_HARD_SEMANTIC_WEIGHT=${PARTFIELD_HARD_SEMANTIC_WEIGHT}"
echo "PARTFIELD_HARD_GEOMETRY_SIGMA=${PARTFIELD_HARD_GEOMETRY_SIGMA}"
echo "PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY=${PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY}"
echo "PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN=${PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN}"
echo "PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR=${PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR}"
echo "PARTFIELD_SEMANTIC_CONFIDENCE_POWER=${PARTFIELD_SEMANTIC_CONFIDENCE_POWER}"
echo "PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT=${PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT}"
echo "PARTFIELD_UNBALANCED_TRANSPORT_RHO=${PARTFIELD_UNBALANCED_TRANSPORT_RHO}"
echo "ARTUR_SOFT_MATCH_SPACE=${ARTUR_SOFT_MATCH_SPACE}"
echo "ARTUR_SOFT_GEOMETRY_SIGMA=${ARTUR_SOFT_GEOMETRY_SIGMA}"
echo "ARTUR_SOFT_SEMANTIC_WEIGHT=${ARTUR_SOFT_SEMANTIC_WEIGHT}"
echo "ARTUR_SOFT_TEMPERATURE=${ARTUR_SOFT_TEMPERATURE}"
echo "PARTFIELD_BALANCED_SINKHORN_ITERS=${PARTFIELD_BALANCED_SINKHORN_ITERS}"
echo "PARTFIELD_MIN_POINTS=${PARTFIELD_MIN_POINTS}"
echo "PARTFIELD_CONTAINMENT_WEIGHT=${PARTFIELD_CONTAINMENT_WEIGHT}"
echo "PARTFIELD_CONTAINMENT_MARGIN=${PARTFIELD_CONTAINMENT_MARGIN}"
echo "PARTFIELD_CONTAINMENT_MAX_WEIGHT=${PARTFIELD_CONTAINMENT_MAX_WEIGHT}"
echo "PARTFIELD_MOMENT_WEIGHT=${PARTFIELD_MOMENT_WEIGHT}"
echo "PARTFIELD_MOMENT_EXTENT_WEIGHT=${PARTFIELD_MOMENT_EXTENT_WEIGHT}"
echo "PARTFIELD_PROFILE_WEIGHT=${PARTFIELD_PROFILE_WEIGHT}"
echo "PARTFIELD_PROFILE_BINS=${PARTFIELD_PROFILE_BINS}"
echo "PARTFIELD_PROFILE_TRIM=${PARTFIELD_PROFILE_TRIM}"
echo "PARTFIELD_ANCHOR_WEIGHT=${PARTFIELD_ANCHOR_WEIGHT}"
echo "PARTFIELD_ANCHOR_GEOMETRY_SIGMA=${PARTFIELD_ANCHOR_GEOMETRY_SIGMA}"
echo "PARTFIELD_ANCHOR_SEMANTIC_WEIGHT=${PARTFIELD_ANCHOR_SEMANTIC_WEIGHT}"
echo "PARTFIELD_LABELS_ALIGNED=${PARTFIELD_LABELS_ALIGNED}"
echo "PARTFIELD_USE_FEATURES=${PARTFIELD_USE_FEATURES}"
echo "SOURCE_PARTFIELD_LABELS=${SOURCE_PARTFIELD_LABELS}"
echo "TARGET_PARTFIELD_LABELS=${TARGET_PARTFIELD_LABELS}"
if [[ "${PARTFIELD_USE_FEATURES}" == "1" ]]; then
  echo "SOURCE_PARTFIELD_FEATURES=${SOURCE_PARTFIELD_FEATURES}"
  echo "TARGET_PARTFIELD_FEATURES=${TARGET_PARTFIELD_FEATURES}"
fi
echo "LOG_INTERVAL_IM=${LOG_INTERVAL_IM}"
echo "SAVE_RENDERS_INTERVAL=${SAVE_RENDERS_INTERVAL}"
echo "EXTRA_LOG_EPOCHS=${EXTRA_LOG_EPOCHS:-}"
echo "SAVE_PCA_VISUALIZATION=${SAVE_PCA_VISUALIZATION}"
echo "PCA_INTERVAL=${PCA_INTERVAL}"
echo "PCA_N_VIEWS=${PCA_N_VIEWS}"
echo "PCA_RENDER_RES=${PCA_RENDER_RES}"
echo "PCA_DINO_MODEL=${PCA_DINO_MODEL}"
echo "PCA_USE_EXTRA_LOG_EPOCHS=${PCA_USE_EXTRA_LOG_EPOCHS}"
echo "OUT=${OUT}"
echo "START_TIME=$(date)"
echo "======================================================"

python main.py \
  --config ./jobs_with_target_guidance/configs/car_partfield_chamfer.yml \
  --mesh "${SOURCE}" \
  --text_prompt "${PROMPT}" \
  --target_mesh "${TARGET}" \
  --no-use_sds \
  --image_weight 0.0 \
  --image_weight_start_factor 0.0 \
  --image_weight_ramp_epochs 0 \
  --loss_schedule independent \
  --deformation_parameterization "${DEFORMATION_PARAMETERIZATION}" \
  --regularize_jacobians_weight "${JACOBIAN_REG_WEIGHT}" \
  --jacobian_neighbor_smooth_weight "${JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT}" \
  --jacobian_outlier_weight "${JACOBIAN_OUTLIER_WEIGHT}" \
  --jacobian_outlier_power "${JACOBIAN_OUTLIER_POWER}" \
  --deformation_grad_clip_norm "${DEFORMATION_GRAD_CLIP_NORM}" \
  --edge_stretch_weight "${EDGE_STRETCH_WEIGHT}" \
  --edge_stretch_threshold "${EDGE_STRETCH_THRESHOLD}" \
  --edge_stretch_max_weight "${EDGE_STRETCH_MAX_WEIGHT}" \
  --edge_displacement_jump_weight "${EDGE_DISPLACEMENT_JUMP_WEIGHT}" \
  --edge_displacement_jump_threshold "${EDGE_DISPLACEMENT_JUMP_THRESHOLD}" \
  --edge_displacement_jump_max_weight "${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT}" \
  "${DINO_LOSS_ARGS[@]}" \
  --no-use_cross_attn_loss \
  "${TARGET_DINO_ARGS[@]}" \
  --target_mesh_chamfer_weight "${GLOBAL_CHAMFER_WEIGHT}" \
  --target_mesh_chamfer_warmup_epochs "${TARGET_CHAMFER_WARMUP_EPOCHS}" \
  --target_mesh_chamfer_points 3072 \
  --target_mesh_vertex_correspondence_weight "${TARGET_VERTEX_CORRESPONDENCE_WEIGHT}" \
  --target_mesh_vertex_correspondence_warmup_epochs "${TARGET_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS}" \
  --target_mesh_semantic_vertex_correspondence_weight "${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT}" \
  --target_mesh_semantic_vertex_correspondence_warmup_epochs "${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WARMUP_EPOCHS}" \
  "${SEMANTIC_VCORR_CACHE_ARGS[@]}" \
  "${SEMANTIC_VCORR_REBUILD_ARGS[@]}" \
  --semantic_vertex_correspondence_label_filter "${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_FILTER}" \
  --semantic_vertex_correspondence_semantic_weight "${SEMANTIC_VERTEX_CORRESPONDENCE_SEMANTIC_WEIGHT}" \
  --semantic_vertex_correspondence_position_weight "${SEMANTIC_VERTEX_CORRESPONDENCE_POSITION_WEIGHT}" \
  --semantic_vertex_correspondence_normal_weight "${SEMANTIC_VERTEX_CORRESPONDENCE_NORMAL_WEIGHT}" \
  --semantic_vertex_correspondence_label_mismatch_penalty "${SEMANTIC_VERTEX_CORRESPONDENCE_LABEL_MISMATCH_PENALTY}" \
  --semantic_vertex_correspondence_topk "${SEMANTIC_VERTEX_CORRESPONDENCE_TOPK}" \
  --semantic_vertex_correspondence_min_similarity "${SEMANTIC_VERTEX_CORRESPONDENCE_MIN_SIMILARITY}" \
  --semantic_vertex_correspondence_confidence_margin "${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_MARGIN}" \
  --semantic_vertex_correspondence_confidence_floor "${SEMANTIC_VERTEX_CORRESPONDENCE_CONFIDENCE_FLOOR}" \
  --semantic_vertex_correspondence_nonmutual_weight "${SEMANTIC_VERTEX_CORRESPONDENCE_NONMUTUAL_WEIGHT}" \
  --semantic_vertex_correspondence_topology_prior_weight "${SEMANTIC_VERTEX_CORRESPONDENCE_TOPOLOGY_PRIOR_WEIGHT}" \
  --target_mesh_partfield_chamfer_weight "${PARTFIELD_CHAMFER_WEIGHT}" \
  --target_mesh_partfield_chamfer_warmup_epochs "${PARTFIELD_CHAMFER_WARMUP_EPOCHS}" \
  --target_mesh_partfield_chamfer_points 512 \
  --target_mesh_partfield_chamfer_global_weight 0.0 \
  --partfield_source_labels "${SOURCE_PARTFIELD_LABELS}" \
  --partfield_target_labels "${TARGET_PARTFIELD_LABELS}" \
  "${PARTFIELD_FEATURE_ARGS[@]}" \
  "${PARTFIELD_LABEL_ARGS[@]}" \
  --partfield_label_mode auto \
  --partfield_feature_mode auto \
  --partfield_n_buckets "${N_BUCKETS}" \
  --partfield_min_points "${PARTFIELD_MIN_POINTS}" \
  --partfield_guidance_mode "${PARTFIELD_GUIDANCE_MODE}" \
  --partfield_hard_weight "${PARTFIELD_HARD_WEIGHT}" \
  --partfield_source_to_target_weight "${PARTFIELD_SOURCE_TO_TARGET_WEIGHT}" \
  --partfield_target_to_source_weight "${PARTFIELD_TARGET_TO_SOURCE_WEIGHT}" \
  --partfield_tgt_to_src_robust_scale "${PARTFIELD_TGT_TO_SRC_ROBUST_SCALE}" \
  --partfield_src_to_tgt_unmatched_weight "${PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT}" \
  --partfield_hard_semantic_weight "${PARTFIELD_HARD_SEMANTIC_WEIGHT}" \
  --partfield_hard_geometry_sigma "${PARTFIELD_HARD_GEOMETRY_SIGMA}" \
  --partfield_semantic_confidence_min_similarity "${PARTFIELD_SEMANTIC_CONFIDENCE_MIN_SIMILARITY}" \
  --partfield_semantic_confidence_margin "${PARTFIELD_SEMANTIC_CONFIDENCE_MARGIN}" \
  --partfield_semantic_confidence_floor "${PARTFIELD_SEMANTIC_CONFIDENCE_FLOOR}" \
  --partfield_semantic_confidence_power "${PARTFIELD_SEMANTIC_CONFIDENCE_POWER}" \
  --partfield_unbalanced_transport_weight "${PARTFIELD_UNBALANCED_TRANSPORT_WEIGHT}" \
  --partfield_unbalanced_transport_rho "${PARTFIELD_UNBALANCED_TRANSPORT_RHO}" \
  --partfield_soft_weight "${PARTFIELD_SOFT_WEIGHT}" \
  --partfield_soft_points "${ARTUR_SOFT_POINTS}" \
  --partfield_soft_match_space "${ARTUR_SOFT_MATCH_SPACE}" \
  --partfield_soft_geometry_sigma "${ARTUR_SOFT_GEOMETRY_SIGMA}" \
  --partfield_soft_semantic_weight "${ARTUR_SOFT_SEMANTIC_WEIGHT}" \
  --partfield_soft_temperature "${ARTUR_SOFT_TEMPERATURE}" \
  --partfield_balanced_sinkhorn_iters "${PARTFIELD_BALANCED_SINKHORN_ITERS}" \
  --partfield_containment_weight "${PARTFIELD_CONTAINMENT_WEIGHT}" \
  --partfield_containment_margin "${PARTFIELD_CONTAINMENT_MARGIN}" \
  --partfield_containment_max_weight "${PARTFIELD_CONTAINMENT_MAX_WEIGHT}" \
  --partfield_moment_weight "${PARTFIELD_MOMENT_WEIGHT}" \
  --partfield_moment_extent_weight "${PARTFIELD_MOMENT_EXTENT_WEIGHT}" \
  --partfield_profile_weight "${PARTFIELD_PROFILE_WEIGHT}" \
  --partfield_profile_bins "${PARTFIELD_PROFILE_BINS}" \
  --partfield_profile_trim "${PARTFIELD_PROFILE_TRIM}" \
  --partfield_anchor_weight "${PARTFIELD_ANCHOR_WEIGHT}" \
  --partfield_anchor_geometry_sigma "${PARTFIELD_ANCHOR_GEOMETRY_SIGMA}" \
  --partfield_anchor_semantic_weight "${PARTFIELD_ANCHOR_SEMANTIC_WEIGHT}" \
  --log_interval_im "${LOG_INTERVAL_IM}" \
  ${EXTRA_LOG_EPOCHS:+--extra_log_epochs ${EXTRA_LOG_EPOCHS}} \
  --save_renders_interval "${SAVE_RENDERS_INTERVAL}" \
  "${PCA_ARGS[@]}" \
  --output_path "${OUT}" \
  --epochs "${EPOCHS}"

if [[ "${RUN_EVAL:-0}" == "1" ]]; then
  python jobs_with_target_guidance/evaluate_target_pipeline.py \
    --output-dir "${OUT}" \
    --samples "${EVAL_SAMPLES:-3000}" \
    --part-samples "${EVAL_PART_SAMPLES:-750}"
fi

echo "END_TIME=$(date)"
echo "Finished: ${OUT}"
