import os
import yaml
import torch
import random
import argparse
import numpy as np
# from loop import loop
from loop_tracked import loop

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', help='Path to config file', type=str, default='./base_config.yml')
    parser.add_argument('--output_path', help='Output directory (will be created)', type=str, default=argparse.SUPPRESS)
    parser.add_argument('--gpu', help='GPU index', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--seed', help='Random seed', type=int, default=argparse.SUPPRESS)
    #parameter for the figures
    parser.add_argument('--log',  action='store_true', default=argparse.SUPPRESS)
    parser.add_argument('--no-log',  action='store_false', default=argparse.SUPPRESS, dest='log')
    
    parser.add_argument('--text_prompt', help='Target text prompt', type=str, nargs='+', default=argparse.SUPPRESS)
    # Mesh
    parser.add_argument('--mesh', help='Path to input mesh', type=str, default=argparse.SUPPRESS)
    parser.add_argument('--retriangulate', help='Use isotropic remeshing', type=int, default=argparse.SUPPRESS, choices=[0, 1])
    parser.add_argument('--texture', help='Path to texture', type=str, default=argparse.SUPPRESS)

    # Locality => this capability is to be announced
    parser.add_argument('--local_weight', help='Enables local weighting for vertices', action='store_true', default=argparse.SUPPRESS)
    parser.add_argument('--no-local_weight', help='Enables local weighting for vertices', action='store_false', default=argparse.SUPPRESS, dest='local_weight')
    parser.add_argument('--target_vertice', type=str, help='Enables local weighting for vertices', default=argparse.SUPPRESS, nargs='+')
    parser.add_argument('--local_def', help='Enables local deformation', type=int, default=0, choices=[0, 1])

    # Render settings
    parser.add_argument('--bsdf', help='Render technique', type=str, default=argparse.SUPPRESS, choices=['diffuse', 'pbr'])

    # Hyper-parameters
    parser.add_argument('--lr', help='Learning rate', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--epochs', help='Number of optimization steps', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--use_sds', help='Enable SDS/diffusion guidance', action='store_true', default=argparse.SUPPRESS)
    parser.add_argument('--no-use_sds', help='Disable SDS/diffusion guidance', action='store_false', default=argparse.SUPPRESS, dest='use_sds')
    parser.add_argument('--image_weight', help='Weight for SDS image loss', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--image_weight_start_factor', help='Initial multiplier for image_weight, linearly ramped to 1', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--image_weight_ramp_epochs', help='Epochs for ramping image_weight from start_factor to 1', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule', help='Schedule for interpolating SDS and target losses', type=str, choices=['independent', 'cosine', 'two_stage', 'three_stage'], default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_epochs', help='Epochs for cosine loss interpolation', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_stage1_epochs', help='Stage 1 length for two/three-stage schedules', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_stage2_epochs', help='Stage 2 end epoch for three-stage schedules', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_sds_start', help='Initial SDS multiplier for scheduled losses', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_sds_mid', help='Middle SDS multiplier for three-stage schedule', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--loss_schedule_target_floor', help='Final/floor target-loss multiplier for scheduled losses', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--deformation_parameterization', help='Trainable deformation representation', type=str, choices=['jacobian', 'vertex'], default=argparse.SUPPRESS)
    parser.add_argument('--regularize_jacobians_weight', help='Weight for jacobian regularization', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--regularize_jacobians_local_weight', help='Weight for local jacobian regularization', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--jacobian_neighbor_smooth_weight', help='Weight for neighboring-face Jacobian smoothness', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--jacobian_outlier_weight', help='Weight for outlier-sensitive per-face Jacobian norm regularization', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--jacobian_outlier_power', help='Power used by outlier-sensitive Jacobian norm regularization', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--deformation_grad_clip_norm', help='Optional gradient-norm clipping for deformation parameters', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_stretch_weight', help='Weight for penalizing over-stretched mesh edges', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_stretch_threshold', help='Allowed edge length ratio before edge-stretch penalty applies', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_stretch_max_weight', help='Extra max-violation weight for suppressing isolated stretched edges', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_displacement_jump_weight', help='Weight for penalizing isolated vertex displacement jumps across mesh edges', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_displacement_jump_threshold', help='Allowed neighbor displacement difference ratio before jump penalty applies', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--edge_displacement_jump_max_weight', help='Extra max-violation weight for suppressing isolated displacement spikes', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--batch_size', help='Number of images rendered at the same time', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--accum_iter', help='Number of images rendered at the same time', type=int, default=argparse.SUPPRESS)
    parser.add_argument('--resize_method', help='Image downsampling/upsampling method', type=str, default=argparse.SUPPRESS, choices=['cubic', 'linear', 'lanczos2', 'lanczos3'])

    ## Camera Parameters ##
    parser.add_argument('--fov_min', help='Minimum camera field of view angle during renders', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--fov_max', help='Maximum camera field of view angle during renders', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--dist_min', help='Minimum distance of camera from mesh during renders', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--dist_max', help='Maximum distance of camera from mesh during renders', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--light_power', help='Light intensity', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--elev_alpha', help='Alpha parameter for Beta distribution for elevation sampling', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--elev_beta', help='Beta parameter for Beta distribution for elevation sampling', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--elev_max', help='Maximum elevation angle in degree', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--azim_min', help='Minimum azimuth angle in degree',  type=float, default=argparse.SUPPRESS)
    parser.add_argument('--azim_max', help='Maximum azimuth angle in degree', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--aug_loc', help='Offset mesh from center of image?', type=int, default=argparse.SUPPRESS, choices=[0, 1])
    parser.add_argument('--aug_light', help='Augment the direction of light around the camera', type=int, default=argparse.SUPPRESS, choices=[0, 1])
    parser.add_argument('--aug_bkg', help='Augment the background', type=int, default=argparse.SUPPRESS, choices=[0, 1])
    parser.add_argument('--adapt_dist', help='Adjust camera distance to account for scale of shape', type=int, default=argparse.SUPPRESS, choices=[0, 1])

    #diffusion
    parser.add_argument('--model_size', type=str, default=argparse.SUPPRESS)
    parser.add_argument('--dtype', type=str, default=argparse.SUPPRESS)
    parser.add_argument('--cpu_offload', action='store_true', default=argparse.SUPPRESS)
    parser.add_argument('--no-cpu_offload', action='store_false', default=argparse.SUPPRESS, dest='cpu_offload')
    parser.add_argument('--score', type=str, default=argparse.SUPPRESS)
    parser.add_argument('--guidance_scale', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--replace_alpha', type=float, default=argparse.SUPPRESS)
    parser.add_argument('--modified_cfg', action='store_true', default=argparse.SUPPRESS)
    parser.add_argument('--no-modified_cfg', action='store_false', default=argparse.SUPPRESS)

    # Logging
    parser.add_argument('--log_interval', help='Interval for logging, every X epochs',  type=int, default=argparse.SUPPRESS)
    parser.add_argument('--log_interval_im', help='Interval for logging renders image, every X epochs',  type=int, default=argparse.SUPPRESS)
    parser.add_argument('--extra_log_epochs', help='Additional exact epoch numbers to save mesh/correspondence artifacts', type=int, nargs='+', default=argparse.SUPPRESS)
    parser.add_argument('--log_mesh', action='store_true', help='Log mesh previews to TensorBoard', default=argparse.SUPPRESS)
    parser.add_argument('--no-log_mesh', action='store_false', dest='log_mesh', default=argparse.SUPPRESS)

    #argmuments used for Blending 
    #this can be a list
    parser.add_argument('--attn_ctrl', action='store_true', help='Turn on blending capabilities', default=argparse.SUPPRESS)
    parser.add_argument('--attn_ctrl_alphas', type=float, nargs='+', default=argparse.SUPPRESS)

    # DINOv2 Semantic Correspondence Loss
    parser.add_argument('--use_dino_loss', action='store_true', help='Enable DINOv2 feature consistency loss for semantic correspondence', default=argparse.SUPPRESS)
    parser.add_argument('--no-use_dino_loss', action='store_false', dest='use_dino_loss', default=argparse.SUPPRESS)
    parser.add_argument('--dino_model', type=str, help='DINOv2 model variant (for example dinov2_vits14_reg, dinov2_vitb14_reg, dinov2_vitl14_reg)', default=argparse.SUPPRESS)
    parser.add_argument('--dino_weight', type=float, help='Weight for DINO loss', default=argparse.SUPPRESS)
    parser.add_argument('--dino_warmup_epochs', type=int, help='Epochs before DINO loss fully activates', default=argparse.SUPPRESS)

    # Cross-Attention Semantic Guidance (can be used alone or with DINO)
    parser.add_argument('--use_cross_attn_loss', action='store_true', help='Enable cross-attention semantic guidance', default=argparse.SUPPRESS)
    parser.add_argument('--no-use_cross_attn_loss', action='store_false', dest='use_cross_attn_loss', default=argparse.SUPPRESS)
    parser.add_argument('--cross_attn_weight', type=float, help='Weight for cross-attention loss', default=argparse.SUPPRESS)
    parser.add_argument('--cross_attn_warmup_epochs', type=int, help='Epochs before cross-attention loss fully activates', default=argparse.SUPPRESS)

    # Target Mesh Guidance (mesh-to-mesh semantic guidance)
    parser.add_argument('--use_target_mesh_guidance', action='store_true', help='Enable target mesh DINO guidance', default=argparse.SUPPRESS)
    parser.add_argument('--no-use_target_mesh_guidance', action='store_false', dest='use_target_mesh_guidance', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh', type=str, help='Path to target mesh file', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_weight', type=float, help='Weight for target mesh guidance loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_warmup_epochs', type=int, help='Epochs before target mesh guidance fully activates', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_dino_model', type=str, help='DINO model for target mesh guidance', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_n_views', type=int, help='Number of target mesh views (V1 guidance)', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_n_azimuths', type=int, help='Number of azimuth bins (V2 guidance)', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_n_elevations', type=int, help='Number of elevation bins (V2 guidance)', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_global_weight', type=float, help='Weight for global target feature matching', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_spatial_weight', type=float, help='Weight for spatial target feature matching', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_render_weight', type=float, help='Weight for aligned target render matching (V2 online guidance)', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_chamfer_weight', type=float, help='Weight for symmetric target mesh Chamfer geometry loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_chamfer_warmup_epochs', type=int, help='Epochs for target mesh Chamfer warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_chamfer_points', type=int, help='Number of source/target vertices sampled for Chamfer loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_vertex_correspondence_weight', type=float, help='Weight for direct vertex-to-vertex target loss when source/target topology matches', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_vertex_correspondence_warmup_epochs', type=int, help='Epochs for direct topology-matched target vertex loss warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_vertex_correspondence_weight', type=float, help='Weight for semantic source-vertex to target-vertex correspondence loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_vertex_correspondence_warmup_epochs', type=int, help='Epochs for semantic vertex correspondence warmup', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_cache', type=str, help='Optional NPZ cache path for semantic source-to-target vertex map', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_rebuild_cache', action='store_true', help='Rebuild semantic vertex correspondence cache even if it exists', default=argparse.SUPPRESS)
    parser.add_argument('--no-semantic_vertex_correspondence_rebuild_cache', action='store_false', dest='semantic_vertex_correspondence_rebuild_cache', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_label_filter', type=str, choices=['none', 'soft', 'hard'], help='How PartField labels constrain semantic vertex matches', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_semantic_weight', type=float, help='PartField descriptor weight for semantic vertex matches', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_position_weight', type=float, help='Normalized XYZ weight for semantic vertex matches', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_normal_weight', type=float, help='Vertex-normal weight for semantic vertex matches', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_label_mismatch_penalty', type=float, help='Soft penalty for matching across different semantic labels', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_topk', type=int, help='Candidate target vertices reranked per source vertex', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_min_similarity', type=float, help='Minimum PartField cosine similarity for full confidence', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_confidence_margin', type=float, help='Cost margin needed for full correspondence confidence', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_confidence_floor', type=float, help='Minimum retained correspondence loss weight', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_nonmutual_weight', type=float, help='Weight multiplier for non-mutual nearest correspondences', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_vertex_correspondence_topology_prior_weight', type=float, help='Bonus tolerance for keeping identity matches when topology already matches', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_weight', type=float, help='Weight for part-aware target mesh Chamfer geometry loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_warmup_epochs', type=int, help='Epochs for part-aware target mesh Chamfer warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_points', type=int, help='Number of vertices sampled per part for part-aware Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_schema', type=str, help='Part schema for part-aware Chamfer, e.g. car or bbox', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_min_points', type=int, help='Minimum source/target vertices required for an active part', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_global_weight', type=float, help='Optional small global Chamfer mixed into part-aware Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_long_axis', type=str, choices=['x', 'y', 'z'], help='Longitudinal axis for part-aware Chamfer labels', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_lateral_axis', type=str, choices=['x', 'y', 'z'], help='Lateral axis for part-aware Chamfer labels', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_vertical_axis', type=str, choices=['x', 'y', 'z'], help='Vertical axis for part-aware Chamfer labels', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_part_chamfer_flip_target_longitudinal', action='store_true', help='Flip target front/rear part labels if target mesh orientation is reversed', default=argparse.SUPPRESS)
    parser.add_argument('--no-target_mesh_part_chamfer_flip_target_longitudinal', action='store_false', dest='target_mesh_part_chamfer_flip_target_longitudinal', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_bucket_chamfer_weight', type=float, help='Weight for rendered-DINO semantic-bucket target Chamfer loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_bucket_chamfer_warmup_epochs', type=int, help='Epochs for semantic-bucket Chamfer warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_bucket_chamfer_points', type=int, help='Number of vertices sampled per semantic bucket', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_semantic_bucket_chamfer_global_weight', type=float, help='Optional global Chamfer mixed into semantic-bucket Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_dino_model', type=str, help='DINO model used to build rendered semantic buckets', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_n_buckets', type=int, help='Number of rendered-DINO semantic buckets', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_n_views', type=int, help='Number of rendered views used for semantic buckets', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_image_size', type=int, help='Render/DINO image size for semantic buckets', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_position_weight', type=float, help='Position-feature weight mixed into semantic-bucket clustering', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_normal_weight', type=float, help='Normal-feature weight mixed into semantic-bucket clustering', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_min_points', type=int, help='Minimum source/target vertices required for an active semantic bucket', default=argparse.SUPPRESS)
    parser.add_argument('--semantic_bucket_cache', type=str, help='Optional path for cached semantic bucket labels', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_sampart3d_chamfer_weight', type=float, help='Weight for SAMPart3D-label target Chamfer loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_sampart3d_chamfer_warmup_epochs', type=int, help='Epochs for SAMPart3D-label Chamfer warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_sampart3d_chamfer_points', type=int, help='Number of vertices sampled per SAMPart3D bucket', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_sampart3d_chamfer_global_weight', type=float, help='Optional global Chamfer mixed into SAMPart3D-label Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_source_labels', type=str, help='Path to source SAMPart3D labels, e.g. mesh_0.5.npy', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_target_labels', type=str, help='Path to target SAMPart3D labels, e.g. mesh_0.5.npy', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_label_mode', type=str, choices=['auto', 'vertex', 'face'], help='Whether SAMPart3D labels are vertex-level or face-level', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_min_points', type=int, help='Minimum source/target vertices required for active SAMPart3D bucket', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_match_centroid_weight', type=float, help='Centroid weight for matching target SAMPart3D parts to source buckets', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_match_extent_weight', type=float, help='Extent weight for matching target SAMPart3D parts to source buckets', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_match_size_weight', type=float, help='Size weight for matching target SAMPart3D parts to source buckets', default=argparse.SUPPRESS)
    parser.add_argument('--sampart3d_debug_path', type=str, help='Optional path for saved SAMPart3D bucket labels/debug JSON', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_partfield_chamfer_weight', type=float, help='Weight for PartField-feature target Chamfer loss', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_partfield_chamfer_warmup_epochs', type=int, help='Epochs for PartField Chamfer warmup', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_partfield_chamfer_points', type=int, help='Number of vertices sampled per PartField bucket', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_partfield_chamfer_global_weight', type=float, help='Optional global Chamfer mixed into PartField Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_source_features', type=str, help='Path to source PartField feature array', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_target_features', type=str, help='Path to target PartField feature array', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_source_labels', type=str, help='Optional path to source PartField clustered labels', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_target_labels', type=str, help='Optional path to target PartField clustered labels', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_feature_mode', type=str, choices=['auto', 'vertex', 'face'], help='Whether PartField features are vertex-level or face-level', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_label_mode', type=str, choices=['auto', 'vertex', 'face'], help='Whether PartField labels are vertex-level or face-level', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_labels_aligned', action='store_true', help='Treat source/target PartField label ids as already aligned across meshes', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_n_buckets', type=int, help='Number of source PartField buckets to build from features', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_min_points', type=int, help='Minimum source/target vertices required for active PartField bucket', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_position_weight', type=float, help='Small normalized XYZ weight mixed into PartField clustering', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_normal_weight', type=float, help='Small normal weight mixed into PartField clustering', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_guidance_mode', type=str, choices=['hard', 'soft', 'hybrid', 'balanced', 'hard_unbalanced'], help='Use hard buckets, soft PartField feature guidance, balanced/unbalanced bucket transport, or both hard+soft', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_hard_weight', type=float, help='Relative weight for hard bucket PartField Chamfer inside hybrid mode', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_source_to_target_weight', type=float, help='Directional weight for source-to-target nearest-neighbor term inside hard PartField Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_target_to_source_weight', type=float, help='Directional weight for target-to-source nearest-neighbor term inside hard PartField Chamfer', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_tgt_to_src_robust_scale', type=float, help='Geman-McClure scale for target-to-source PartField Chamfer; 0 disables, negative uses the per-bucket median NN distance', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_src_to_tgt_unmatched_weight', type=float, help='Relative source-to-target weight for source samples not selected by any reverse target-to-source nearest neighbor', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_hard_semantic_weight', type=float, help='PartField feature distance weight used when choosing hard-bucket nearest neighbors', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_hard_geometry_sigma', type=float, help='Unit-space geometry sigma used in hard-bucket feature-guided matching cost', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_semantic_confidence_min_similarity', type=float, help='Minimum cosine similarity for semantic confidence gating; <= -1 disables this gate', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_semantic_confidence_margin', type=float, help='Top-1 minus top-2 cosine margin needed for full semantic confidence; 0 disables margin gating', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_semantic_confidence_floor', type=float, help='Minimum retained weight for ambiguous semantic matches; 1 disables confidence gating', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_semantic_confidence_power', type=float, help='Power applied to semantic confidence before blending with the floor', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_unbalanced_transport_weight', type=float, help='Extra unbalanced Sinkhorn bucket-transport weight added in hard_unbalanced mode', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_unbalanced_transport_rho', type=float, help='KL marginal relaxation for unbalanced Sinkhorn bucket transport', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_weight', type=float, help='Relative weight for soft PartField feature guidance inside hybrid/soft mode', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_points', type=int, help='Number of source/target vertices sampled for soft PartField feature guidance', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_semantic_weight', type=float, help='Semantic feature distance weight in soft PartField matching cost', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_temperature', type=float, help='Softmax temperature for semantic PartField matching', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_match_space', type=str, choices=['latent', 'geometry', 'hybrid'], help='Space used to build soft PartField correspondences', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_soft_geometry_sigma', type=float, help='Geometry sigma for Artur-style soft PartField matching cost', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_balanced_sinkhorn_iters', type=int, help='Sinkhorn iterations for balanced PartField bucket transport', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_containment_weight', type=float, help='Relative weight for keeping source vertices inside matching target PartField bucket bounds', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_containment_margin', type=float, help='Unit-space margin around target PartField bucket bounds before containment penalty applies', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_containment_max_weight', type=float, help='Extra max-violation weight for PartField containment to suppress isolated spikes', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_moment_weight', type=float, help='Relative weight for matching per-PartField-bucket centroid and RMS spread to the target', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_moment_extent_weight', type=float, help='RMS-spread-vs-centroid balance inside the PartField moment loss', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_profile_weight', type=float, help='Relative weight for matching per-PartField-bucket trimmed coordinate quantile profiles to the target', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_profile_bins', type=int, help='Number of coordinate quantiles used in the PartField profile loss', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_profile_trim', type=float, help='Fraction of each PartField bucket coordinate distribution trimmed at both ends for profile loss', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_anchor_weight', type=float, help='Relative weight for fixed semantic target anchors inside active PartField buckets', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_anchor_geometry_sigma', type=float, help='Unit-space geometry sigma used to pick fixed PartField target anchors', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_anchor_semantic_weight', type=float, help='PartField feature distance weight used to pick fixed target anchors', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_cache', type=str, help='Optional path for cached PartField bucket labels', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_debug_path', type=str, help='Optional path for saved PartField bucket labels/debug JSON', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_enabled', action='store_true', help='Use staged coarse-to-fine PartField bucket losses', default=argparse.SUPPRESS)
    parser.add_argument('--no-partfield_multiscale_enabled', action='store_false', dest='partfield_multiscale_enabled', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_buckets', type=int, nargs='+', help='PartField bucket counts used from coarse to fine, e.g. 8 12 20', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_stage_epochs', type=int, nargs='+', help='Epochs where each PartField scale starts; defaults to even splits', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_blend_epochs', type=int, help='Epochs used to blend from one PartField scale into the next', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_source_labels', type=str, nargs='+', help='Source label NPZ paths for each PartField scale', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_target_labels', type=str, nargs='+', help='Target label NPZ paths for each PartField scale', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_label_dirs', type=str, nargs='+', help='Directories containing labels/ for each PartField scale', default=argparse.SUPPRESS)
    parser.add_argument('--partfield_multiscale_cache_dir', type=str, help='Directory for multi-scale PartField label caches/debug files', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_online_render', action='store_true', help='Render target mesh online using current training cameras (stronger alignment)', default=argparse.SUPPRESS)
    parser.add_argument('--no-target_mesh_online_render', action='store_false', dest='target_mesh_online_render', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_online_cache', action='store_true', help='Cache online target features by quantized camera params', default=argparse.SUPPRESS)
    parser.add_argument('--no-target_mesh_online_cache', action='store_false', dest='target_mesh_online_cache', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_online_cache_max', type=int, help='Maximum cached camera entries for online target features', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_view_rounding_deg', type=float, help='Camera azimuth/elevation quantization in degrees for online cache', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_view_rounding_dist', type=float, help='Camera distance quantization for online cache', default=argparse.SUPPRESS)
    parser.add_argument('--target_mesh_view_rounding_fov', type=float, help='Camera FOV quantization for online cache', default=argparse.SUPPRESS)

    # Semantic Tracking & Visualization
    parser.add_argument('--track_correspondence', action='store_true', help='Enable vertex correspondence tracking', default=argparse.SUPPRESS)
    parser.add_argument('--no-track_correspondence', action='store_false', dest='track_correspondence', default=argparse.SUPPRESS)
    parser.add_argument('--color_method', type=str, choices=['position', 'dino_pca'], help='Method for coloring vertices: position (XYZ->RGB) or dino_pca (semantic)', default=argparse.SUPPRESS)
    parser.add_argument('--dino_pca_model', type=str, help='DINO model for semantic vertex coloring', default=argparse.SUPPRESS)
    parser.add_argument('--dino_pca_n_views', type=int, help='Number of views for DINO PCA vertex coloring', default=argparse.SUPPRESS)
    parser.add_argument('--dino_pca_image_size', type=int, help='Image size for DINO PCA vertex coloring', default=argparse.SUPPRESS)

    # Combined 2D PCA Visualization over training epochs
    parser.add_argument('--save_pca_visualization', action='store_true', help='Save semantic PCA visualizations during training', default=argparse.SUPPRESS)
    parser.add_argument('--no-save_pca_visualization', action='store_false', dest='save_pca_visualization', default=argparse.SUPPRESS)
    parser.add_argument('--pca_interval', type=int, help='Interval for PCA visualization snapshots', default=argparse.SUPPRESS)
    parser.add_argument('--pca_n_views', type=int, help='Number of camera views used for PCA visualization', default=argparse.SUPPRESS)
    parser.add_argument('--pca_render_res', type=int, help='Render resolution for PCA visualization', default=argparse.SUPPRESS)
    parser.add_argument('--pca_dino_model', type=str, help='DINO model for combined PCA visualization', default=argparse.SUPPRESS)
    parser.add_argument('--pca_use_extra_log_epochs', action='store_true', help='Also save PCA snapshots at exact extra_log_epochs', default=argparse.SUPPRESS)
    parser.add_argument('--no-pca_use_extra_log_epochs', action='store_false', dest='pca_use_extra_log_epochs', default=argparse.SUPPRESS)

    # Epoch Render Saving (for visual tracking)
    parser.add_argument('--save_epoch_renders', action='store_true', help='Save rendered images at each log interval', default=argparse.SUPPRESS)
    parser.add_argument('--no-save_epoch_renders', action='store_false', dest='save_epoch_renders', default=argparse.SUPPRESS)
    parser.add_argument('--save_renders_interval', type=int, help='Interval for saving renders (defaults to log_interval_im)', default=argparse.SUPPRESS)
    parser.add_argument('--epoch_render_res', type=int, help='Resolution for epoch render images', default=argparse.SUPPRESS)

    args = parser.parse_args()
    if args.config is not None:
        with open(args.config, 'r') as f:
            try:
                cfg = yaml.safe_load(f)
            except yaml.YAMLError as e:
                print(e)
    
    for key in vars(args):
        cfg[key] = vars(args)[key]

    print(yaml.dump(cfg, default_flow_style=False))
    random.seed(cfg['seed'])
    os.environ['PYTHONHASHSEED'] = str(cfg['seed'])
    np.random.seed(cfg['seed'])
    torch.manual_seed(cfg['seed'])
    torch.cuda.manual_seed(cfg['seed'])
    torch.backends.cudnn.deterministic = True

    loop(cfg)
    print('Done')

if __name__ == '__main__':
    main()
