#!/bin/bash
set -euo pipefail

if [[ "$#" -lt 4 ]]; then
  echo "Usage: $0 SOURCE_OBJECT TARGET_OBJECT EPOCHS OUTPUT_ROOT [RUN_TAG]"
  echo "Example objects: 071b8_toy_animals_017 13cf7_toy_animals_055"
  exit 2
fi

SOURCE_OBJECT="$1"
TARGET_OBJECT="$2"
EPOCHS="$3"
OUTPUT_ROOT="$4"
RUN_TAG="${5:-densecorr3d_animals}"

cd /pfs/work9/workspace/scratch/fr_rl187-my_project_ws/projects/meshup_v2
source ./activate_meshup_new.sh

BASE_DIR=${BASE_DIR:-./jobs_with_target_guidance/densematcher_runs}
DENSECORR3D_ROOT=${DENSECORR3D_ROOT:-./external/DenseCorr3D}
DENSECORR3D_CATEGORY=${DENSECORR3D_CATEGORY:-animals}
DENSECORR3D_SEGMENT_DIR=${DENSECORR3D_SEGMENT_DIR:-${BASE_DIR}/densecorr3d/${DENSECORR3D_CATEGORY}}

SOURCE_DIR="${DENSECORR3D_ROOT}/${DENSECORR3D_CATEGORY}/${SOURCE_OBJECT}"
TARGET_DIR="${DENSECORR3D_ROOT}/${DENSECORR3D_CATEGORY}/${TARGET_OBJECT}"
SOURCE="${SOURCE_DIR}/simple_mesh.obj"
TARGET="${TARGET_DIR}/simple_mesh.obj"
SOURCE_PARTFIELD_LABELS="${DENSECORR3D_SEGMENT_DIR}/labels/${SOURCE_OBJECT}_densecorr3d_labels.npz"
TARGET_PARTFIELD_LABELS="${DENSECORR3D_SEGMENT_DIR}/labels/${TARGET_OBJECT}_densecorr3d_labels.npz"

if [[ ! -f "${SOURCE}" || ! -f "${TARGET}" ]]; then
  echo "Missing DenseCorr3D meshes."
  echo "Expected source: ${SOURCE}"
  echo "Expected target: ${TARGET}"
  echo "Set DENSECORR3D_ROOT to the unzipped DenseCorr3D directory."
  exit 1
fi

if [[ ! -f "${SOURCE_PARTFIELD_LABELS}" || ! -f "${TARGET_PARTFIELD_LABELS}" ]]; then
  python jobs_with_target_guidance/densecorr3d_segment.py \
    --densecorr3d-root "${DENSECORR3D_ROOT}" \
    --category "${DENSECORR3D_CATEGORY}" \
    --objects "${SOURCE_OBJECT}" "${TARGET_OBJECT}" \
    --output-dir "${DENSECORR3D_SEGMENT_DIR}"
fi

PAIR_SLUG="${SOURCE_OBJECT}_to_${TARGET_OBJECT}"
PROMPT=${PROMPT:-"an animal"}

export SOURCE
export TARGET
export SOURCE_NAME="${SOURCE_OBJECT}"
export TARGET_NAME="${TARGET_OBJECT}"
export PAIR_SLUG
export PROMPT
export SOURCE_PARTFIELD_LABELS
export TARGET_PARTFIELD_LABELS
export PARTFIELD_USE_FEATURES=0
export PARTFIELD_LABELS_ALIGNED=${PARTFIELD_LABELS_ALIGNED:-1}
export PARTFIELD_N_BUCKETS=${PARTFIELD_N_BUCKETS:-12}
export PARTFIELD_CHAMFER_WEIGHT_OVERRIDE=${PARTFIELD_CHAMFER_WEIGHT_OVERRIDE:-8000.0}
export PARTFIELD_GUIDANCE_MODE=${PARTFIELD_GUIDANCE_MODE:-hard}
export PARTFIELD_HARD_WEIGHT=${PARTFIELD_HARD_WEIGHT:-1.0}
export PARTFIELD_SOFT_WEIGHT=${PARTFIELD_SOFT_WEIGHT:-0.0}
export PARTFIELD_SOURCE_TO_TARGET_WEIGHT=${PARTFIELD_SOURCE_TO_TARGET_WEIGHT:-0.35}
export PARTFIELD_TARGET_TO_SOURCE_WEIGHT=${PARTFIELD_TARGET_TO_SOURCE_WEIGHT:-1.0}
export PARTFIELD_TGT_TO_SRC_ROBUST_SCALE=${PARTFIELD_TGT_TO_SRC_ROBUST_SCALE:-0.0}
export PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT=${PARTFIELD_SRC_TO_TGT_UNMATCHED_WEIGHT:-1.0}
export PARTFIELD_MIN_POINTS=${PARTFIELD_MIN_POINTS:-8}
export DEFORMATION_PARAMETERIZATION=${DEFORMATION_PARAMETERIZATION:-jacobian}
export JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT=${JACOBIAN_NEIGHBOR_SMOOTH_WEIGHT:-1000.0}
export EDGE_DISPLACEMENT_JUMP_WEIGHT=${EDGE_DISPLACEMENT_JUMP_WEIGHT:-500.0}
export EDGE_DISPLACEMENT_JUMP_THRESHOLD=${EDGE_DISPLACEMENT_JUMP_THRESHOLD:-1.2}
export EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT=${EDGE_DISPLACEMENT_JUMP_MAX_WEIGHT:-2.0}
export TARGET_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_VERTEX_CORRESPONDENCE_WEIGHT:-0.0}
export TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT=${TARGET_SEMANTIC_VERTEX_CORRESPONDENCE_WEIGHT:-0.0}
export GLOBAL_CHAMFER_WEIGHT_OVERRIDE=${GLOBAL_CHAMFER_WEIGHT_OVERRIDE:-0.0}
export ENABLE_SOURCE_DINO_LOSS=${ENABLE_SOURCE_DINO_LOSS:-0}
export ENABLE_TARGET_DINO_GUIDANCE=${ENABLE_TARGET_DINO_GUIDANCE:-0}
export LOG_INTERVAL_IM=${LOG_INTERVAL_IM:-50}
export SAVE_RENDERS_INTERVAL=${SAVE_RENDERS_INTERVAL:-50}
export VARIANT_SUFFIX=${VARIANT_SUFFIX:-densecorr3d_groups}

bash ./jobs_with_target_guidance/artur_soft_runs/jobs/run_artur_chamfer_ablation.sh \
  1 \
  "${EPOCHS}" \
  "${OUTPUT_ROOT}" \
  "${RUN_TAG}"
